exclude: '^$|settings|scripts|docs'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)^(
                .*README.md|
                .*\.f90
            )$
        # let flake8 deal with py => dont treat docstrings.
        exclude_types: ['html','python']
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
        exclude: 'dapper/tools/liveplotting.py'
    -   id: detect-aws-credentials  # Notifies if you DONT have credentials
        args:
        - --allow-missing-credentials
    -   id: detect-private-key  # Notifies if you have private
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: ['--fix=no']

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
    - id: ruff

-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: |
            (?x)^(
                examples/.*.py
            )$
