exclude: '^$|settings|scripts|docs'

repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)^(
                .*README.md|
                .*\.f90
            )$
        # let flake8 deal with py => dont treat docstrings.
        exclude_types: ['html','python']
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
        exclude: 'dapper/tools/liveplotting.py'
    -   id: detect-aws-credentials  # Notifies if you DONT have credentials
        args:
        - --allow-missing-credentials
    -   id: detect-private-key  # Notifies if you have private
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: ['--fix=no']

-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: [--max-line-length=88]  # default of Black
